version: '3.8'

services:
  # PHP 應用服務
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/var/www/html
      - ./backend/storage/logs:/var/www/html/storage/logs
    depends_on:
      - mysql
      - redis
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=traffic_monitor
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
      - JWT_SECRET=your_jwt_secret_key

  # 前端服務
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000/api

  # Nginx 服務
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  # MySQL 服務
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=traffic_monitor

  # Redis 服務
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # AI 服務
  ai:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: ai-base
    volumes:
      - ./backend/ai:/app/ai
      - ./backend/storage/videos:/app/storage/videos
    environment:
      - PYTHONUNBUFFERED=1
      - MODEL_PATH=/app/ai/models/yolov5s.pt
    command: python /app/ai/main.py

volumes:
  mysql_data:
  redis_data: 